[workspace]
members = ["programs/orderflow"]

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
orderflow = "7WNQhMKbKhZGYw3zYc77KAHS47hcxss2PCkztQui51fR"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
