[workspace]
members = ["programs/orderflow"]

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
orderflow = "7WNQhMKbKhZGYw3zYc77KAHS47hcxss2PCkztQui51fR"

[scripts]
test = "node ./run-tests.cjs"
